[build]
  publish = "."

[[redirects]]
  from = "/book"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/captain"
  to = "/the-team/"
  status = 301

[[redirects]]
  from = "/crew"
  to = "/the-team/"
  status = 301

[[redirects]]
  from = "/fishing"
  to = "/charters/"
  status = 301

[[redirects]]
  from = "/photos"
  to = "/gallery/"
  status = 301

[[redirects]]
  from = "/savannah"
  to = "https://cadefoundation.org/savannahgrant"
  status = 301
